"""add_metrics_history_table

Revision ID: d13bf77e3e28
Revises: 06b9d79b7efd
Create Date: 2026-03-20 17:09:04.849574
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd13bf77e3e28'
down_revision: Union[str, None] = '06b9d79b7efd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metrics_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('cpu_percent', sa.Float(), nullable=False),
    sa.Column('ram_percent', sa.Float(), nullable=False),
    sa.Column('ram_used_mb', sa.Integer(), nullable=False),
    sa.Column('disk_percent', sa.Float(), nullable=False),
    sa.Column('net_bytes_sent', sa.Integer(), nullable=False),
    sa.Column('net_bytes_recv', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_metrics_history_ts', 'metrics_history', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_metrics_history_ts', table_name='metrics_history')
    op.drop_table('metrics_history')
    # ### end Alembic commands ###
